// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAGAwYRctl_Le91Law-_w9pM9D2MPMRho',
    appId: '1:164100596988:web:ccc061f723265444566379',
    messagingSenderId: '164100596988',
    projectId: 'fitness-freaks-62dfe',
    authDomain: 'fitness-freaks-62dfe.firebaseapp.com',
    storageBucket: 'fitness-freaks-62dfe.appspot.com',
    measurementId: 'G-LVLW3ZEB4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjZSucbmFBLhpmHk5lK-HQPp2wWVqmwnk',
    appId: '1:164100596988:android:6c85f98545a817bb566379',
    messagingSenderId: '164100596988',
    projectId: 'fitness-freaks-62dfe',
    storageBucket: 'fitness-freaks-62dfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPLEjyI9511Hkl_vUO9av6goqJP1aAISE',
    appId: '1:164100596988:ios:b0769aa25dbce23f566379',
    messagingSenderId: '164100596988',
    projectId: 'fitness-freaks-62dfe',
    storageBucket: 'fitness-freaks-62dfe.appspot.com',
    iosBundleId: 'com.example.fitnessFreaks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPLEjyI9511Hkl_vUO9av6goqJP1aAISE',
    appId: '1:164100596988:ios:40e272c47d2187a8566379',
    messagingSenderId: '164100596988',
    projectId: 'fitness-freaks-62dfe',
    storageBucket: 'fitness-freaks-62dfe.appspot.com',
    iosBundleId: 'com.example.fitnessFreaks.RunnerTests',
  );
}
